### ISSUE TITLE
Are the title cards on top of Markdown used at all?

### ISSUE THREAD

**Issue by bast** [coderefinery/github-without-command-line#53]
If not I guess we can remove them?

**Comment by rkdarst** [comment]
They aren't.  I haven't been removing them yet for two reasons:

- In case we go back to jekyll.
- Both rst and myst_parser have a concept of document (page) metadata.  I bet we could use it to write an extension to take the place of structured table of contents like the old jekyll format has.

**Comment by bast** [comment]
I will remove them. I don't see us going back to Jekyll soon.
